"""G04 extracted fields, case fields, issues

Revision ID: 0004_fields_issues
Revises: 0003_documents
Create Date: 2026-10-08 03:30:08.324437
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0004_fields_issues'
down_revision = '0003_documents'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('target_ref', sa.String(length=200), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('auto_resolvable', sa.Boolean(), nullable=False),
    sa.Column('assignee_role', sa.String(length=32), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_by_type', sa.String(length=10), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolution_value', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'dedupe_key')
    )
    op.create_index(op.f('ix_issues_case_id'), 'issues', ['case_id'], unique=False)
    op.create_index(op.f('ix_issues_tenant_id'), 'issues', ['tenant_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('parse_run_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_version', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.String(length=300), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_case_id'), 'extracted_fields', ['case_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_document_id'), 'extracted_fields', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_parse_run_id'), 'extracted_fields', ['parse_run_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_tenant_id'), 'extracted_fields', ['tenant_id'], unique=False)
    op.create_table('case_fields',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=12), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_extracted_field_id', sa.Uuid(), nullable=True),
    sa.Column('source_ref', sa.String(length=300), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('rule_ref', sa.String(length=120), nullable=True),
    sa.Column('alternatives', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_extracted_field_id'], ['extracted_fields.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'key')
    )
    op.create_index(op.f('ix_case_fields_case_id'), 'case_fields', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_fields_tenant_id'), 'case_fields', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_fields_tenant_id'), table_name='case_fields')
    op.drop_index(op.f('ix_case_fields_case_id'), table_name='case_fields')
    op.drop_table('case_fields')
    op.drop_index(op.f('ix_extracted_fields_tenant_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_parse_run_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_document_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_case_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_issues_tenant_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_case_id'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
