"""G05 goods, HS candidates, decisions, knowledge

Revision ID: 0005_goods_hs_knowledge
Revises: 0004_fields_issues
Create Date: 2026-10-08 03:35:07.674344
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0005_goods_hs_knowledge'
down_revision = '0004_fields_issues'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_datasets',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'version')
    )
    op.create_table('hs_rules',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('heading', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('exclusions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('required_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('base_confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['knowledge_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hs_rules_dataset_id'), 'hs_rules', ['dataset_id'], unique=False)
    op.create_table('goods_items',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_vn', sa.Text(), nullable=True),
    sa.Column('description_vn_status', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.String(length=40), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.String(length=40), nullable=True),
    sa.Column('packages', sa.String(length=40), nullable=True),
    sa.Column('origin_criterion', sa.String(length=20), nullable=True),
    sa.Column('co_line_matched', sa.Boolean(), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attribute_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_ref', sa.String(length=300), nullable=True),
    sa.Column('manual_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('hs_code', sa.String(length=12), nullable=True),
    sa.Column('hs_status', sa.String(length=20), nullable=False),
    sa.Column('hs_confidence', sa.Float(), nullable=True),
    sa.Column('hs_decision_id', sa.Uuid(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'line_no')
    )
    op.create_index(op.f('ix_goods_items_case_id'), 'goods_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_goods_items_fingerprint'), 'goods_items', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_goods_items_tenant_id'), 'goods_items', ['tenant_id'], unique=False)
    op.create_table('hs_candidates',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('matched_keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('missing_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('history_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_version', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['knowledge_datasets.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['goods_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hs_candidates_case_id'), 'hs_candidates', ['case_id'], unique=False)
    op.create_index(op.f('ix_hs_candidates_item_id'), 'hs_candidates', ['item_id'], unique=False)
    op.create_index(op.f('ix_hs_candidates_run_id'), 'hs_candidates', ['run_id'], unique=False)
    op.create_index(op.f('ix_hs_candidates_tenant_id'), 'hs_candidates', ['tenant_id'], unique=False)
    op.create_table('classification_decisions',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('hs_code', sa.String(length=12), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=False),
    sa.Column('decided_by_role', sa.String(length=32), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['hs_candidates.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['goods_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_decisions_case_id'), 'classification_decisions', ['case_id'], unique=False)
    op.create_index(op.f('ix_classification_decisions_item_id'), 'classification_decisions', ['item_id'], unique=False)
    op.create_index(op.f('ix_classification_decisions_tenant_id'), 'classification_decisions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classification_decisions_tenant_id'), table_name='classification_decisions')
    op.drop_index(op.f('ix_classification_decisions_item_id'), table_name='classification_decisions')
    op.drop_index(op.f('ix_classification_decisions_case_id'), table_name='classification_decisions')
    op.drop_table('classification_decisions')
    op.drop_index(op.f('ix_hs_candidates_tenant_id'), table_name='hs_candidates')
    op.drop_index(op.f('ix_hs_candidates_run_id'), table_name='hs_candidates')
    op.drop_index(op.f('ix_hs_candidates_item_id'), table_name='hs_candidates')
    op.drop_index(op.f('ix_hs_candidates_case_id'), table_name='hs_candidates')
    op.drop_table('hs_candidates')
    op.drop_index(op.f('ix_goods_items_tenant_id'), table_name='goods_items')
    op.drop_index(op.f('ix_goods_items_fingerprint'), table_name='goods_items')
    op.drop_index(op.f('ix_goods_items_case_id'), table_name='goods_items')
    op.drop_table('goods_items')
    op.drop_index(op.f('ix_hs_rules_dataset_id'), table_name='hs_rules')
    op.drop_table('hs_rules')
    op.drop_table('knowledge_datasets')
    # ### end Alembic commands ###
