"""G06 assessments, issue owner

Revision ID: 0006_assessments
Revises: 0005_goods_hs_knowledge
Create Date: 2026-10-08 03:42:27.230257
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0006_assessments'
down_revision = '0005_goods_hs_knowledge'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('dataset_version', sa.String(length=40), nullable=True),
    sa.Column('dataset_is_demo', sa.Boolean(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reasoning', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reviewer_decision', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['knowledge_datasets.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['goods_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'item_id', 'kind')
    )
    op.create_index(op.f('ix_assessments_case_id'), 'assessments', ['case_id'], unique=False)
    op.create_index(op.f('ix_assessments_item_id'), 'assessments', ['item_id'], unique=False)
    op.create_index(op.f('ix_assessments_tenant_id'), 'assessments', ['tenant_id'], unique=False)
    op.add_column('issues', sa.Column('raised_by', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'raised_by')
    op.drop_index(op.f('ix_assessments_tenant_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_item_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_case_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
