"""G08 declaration drafts

Revision ID: 0007_drafts
Revises: 0006_assessments
Create Date: 2026-10-08 03:48:23.715830
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0007_drafts'
down_revision = '0006_assessments'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('declaration_drafts',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('schema_version', sa.String(length=30), nullable=False),
    sa.Column('release_eligible', sa.Boolean(), nullable=False),
    sa.Column('watermark', sa.String(length=120), nullable=False),
    sa.Column('case_status_at_export', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'version')
    )
    op.create_index(op.f('ix_declaration_drafts_case_id'), 'declaration_drafts', ['case_id'], unique=False)
    op.create_index(op.f('ix_declaration_drafts_tenant_id'), 'declaration_drafts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_declaration_drafts_tenant_id'), table_name='declaration_drafts')
    op.drop_index(op.f('ix_declaration_drafts_case_id'), table_name='declaration_drafts')
    op.drop_table('declaration_drafts')
    # ### end Alembic commands ###
