"""G09-G10 copilot messages, proposals, product memory

Revision ID: 0008_copilot_memory
Revises: 0007_drafts
Create Date: 2026-10-08 03:56:11.657007
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0008_copilot_memory'
down_revision = '0007_drafts'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_messages',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=5), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=True),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reasoning', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_version', sa.String(length=50), nullable=True),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_messages_case_id'), 'copilot_messages', ['case_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_tenant_id'), 'copilot_messages', ['tenant_id'], unique=False)
    op.create_table('proposals',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_ref', sa.String(length=80), nullable=False),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_case_id'), 'proposals', ['case_id'], unique=False)
    op.create_index(op.f('ix_proposals_tenant_id'), 'proposals', ['tenant_id'], unique=False)
    op.create_table('product_memory',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('case_no', sa.String(length=40), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('model_norm', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_vn', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.String(length=12), nullable=False),
    sa.Column('heading', sa.String(length=4), nullable=False),
    sa.Column('unit_price', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('co_form', sa.String(length=10), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by_role', sa.String(length=32), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('reusable', sa.Boolean(), nullable=False),
    sa.Column('outcome_reason', sa.Text(), nullable=True),
    sa.Column('outcome_set_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['classification_decisions.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['goods_items.id'], ),
    sa.ForeignKeyConstraint(['outcome_set_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_index(op.f('ix_product_memory_customer_id'), 'product_memory', ['customer_id'], unique=False)
    op.create_index(op.f('ix_product_memory_fingerprint'), 'product_memory', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_product_memory_model'), 'product_memory', ['model'], unique=False)
    op.create_index(op.f('ix_product_memory_model_norm'), 'product_memory', ['model_norm'], unique=False)
    op.create_index(op.f('ix_product_memory_tenant_id'), 'product_memory', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_memory_tenant_id'), table_name='product_memory')
    op.drop_index(op.f('ix_product_memory_model_norm'), table_name='product_memory')
    op.drop_index(op.f('ix_product_memory_model'), table_name='product_memory')
    op.drop_index(op.f('ix_product_memory_fingerprint'), table_name='product_memory')
    op.drop_index(op.f('ix_product_memory_customer_id'), table_name='product_memory')
    op.drop_table('product_memory')
    op.drop_index(op.f('ix_proposals_tenant_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_case_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_copilot_messages_tenant_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_case_id'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    # ### end Alembic commands ###
