"""G05 widen classification decision for REQUEST_INFO

Revision ID: 0009_decision_request_info
Revises: 0008_copilot_memory
Create Date: 2026-10-08 06:17:51.550692
"""
from alembic import op
import sqlalchemy as sa


revision = '0009_decision_request_info'
down_revision = '0008_copilot_memory'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classification_decisions', 'decision',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classification_decisions', 'decision',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
