"""G09 copilot message meta

Revision ID: 0010_copilot_meta
Revises: 0009_decision_request_info
Create Date: 2026-10-08 06:21:20.204848
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0010_copilot_meta'
down_revision = '0009_decision_request_info'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copilot_messages', sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'{}'::jsonb")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copilot_messages', 'meta')
    # ### end Alembic commands ###
